# Generated by Django 2.0.3 on 2018-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_remove_post_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
