# Generated by Django 2.0.4 on 2018-04-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20180418_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='author',
        ),
    ]
